name: mushroomdetector
description: "Mushroom detector"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.5
  image: ^4.1.3
  camera:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mushroom.tflite
    - assets/mobilenet_quant.tflite
    - assets/labels.txt
    - assets/mobilenet_labels.txt
    - assets/mushroomv2.tflite
    - assets/mushroomv2.txt